# Generated by Django 2.1.3 on 2018-11-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0004_auto_20181109_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriber',
            name='corporate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
