# Generated by Django 2.1.3 on 2018-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0005_prescriber_corporate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriber',
            old_name='corporate',
            new_name='practice_type',
        ),
        migrations.AddField(
            model_name='dispenser',
            name='corporate_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
