# Generated by Django 2.1.3 on 2018-11-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0006_auto_20181114_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='text', max_length=100)),
                ('total_prescriptions', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('model_number', models.FloatField(default=0)),
            ],
        ),
    ]
