# Generated by Django 2.1.3 on 2018-11-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0006_auto_20181114_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispenser',
        ),
    ]
