# Generated by Django 2.1.3 on 2018-11-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0007_removed_dispenser_test_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nester_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nester_name', models.CharField(blank=True, default='', max_length=100)),
                ('nester_number', models.FloatField(default=0)),
                ('nester_description', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nest_model',
            fields=[
                ('nest_name', models.CharField(blank=True, default='', max_length=100)),
                ('nest_number', models.FloatField(default=0)),
                ('nest_description', models.CharField(blank=True, default='', max_length=100)),
                ('nester_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rxitapp.Nester_model')),
            ],
        ),
        migrations.CreateModel(
            name='Test_model',
            fields=[
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('model_number', models.FloatField(default=0)),
                ('nest_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rxitapp.Nest_model')),
            ],
        ),
    ]
