# Generated by Django 2.1.3 on 2018-11-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0007_no_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenser',
            name='id',
        ),
        migrations.AddField(
            model_name='dispenser',
            name='statistics',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rxitapp.DispStat'),
        ),
    ]
