# Generated by Django 2.1.3 on 2018-11-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0008_include_nester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('participant_name', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('corporate_type', models.CharField(blank=True, default='', max_length=100)),
                ('pharmacy_mgt_system', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parmacists', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('num_reg_tech', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('num_unreg', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='RxStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_am', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('num_pm', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('num_evng', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('num_wend', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='dispenser',
            name='numbers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rxitapp.Numbers'),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='rx_stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rxitapp.RxStats'),
        ),
    ]
