# Generated by Django 2.1.3 on 2018-11-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='participant_index',
            field=models.IntegerField(default=0),
        ),
    ]
