# Generated by Django 2.1.3 on 2018-11-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0002_auto_20181109_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='main street', max_length=200),
        ),
    ]
