# Generated by Django 2.1.3 on 2018-11-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0008_include_nester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parmacists', models.DecimalField(decimal_places=1, max_digits=3)),
                ('num_reg_tech', models.DecimalField(decimal_places=1, max_digits=3)),
                ('num_unreg', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('participant_name', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('corporate_type', models.CharField(blank=True, default='', max_length=100)),
                ('numbers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rxitapp.Numbers')),
            ],
        ),
    ]
