# Generated by Django 2.1.3 on 2018-11-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0009_add_walk_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('participant_name', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('corporate_type', models.CharField(blank=True, default='', max_length=100)),
                ('pharmacy_mgt_system', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='corporate_type',
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='participant_name',
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='pharmacy_mgt_system',
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='province',
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='street',
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='username',
        ),
        migrations.AddField(
            model_name='dispenser',
            name='description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rxitapp.Description'),
        ),
    ]
