# Generated by Django 2.1.3 on 2018-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0009_extend_nest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nester_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nester_name', models.CharField(blank=True, default='', max_length=100)),
                ('nester_number', models.FloatField(default=0)),
                ('nester_description', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
