# Generated by Django 2.1.3 on 2018-11-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0010_add_nester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nest_model',
            name='id',
        ),
        migrations.AddField(
            model_name='nest_model',
            name='nester_model',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rxitapp.Nester_model'),
        ),
    ]
