# Generated by Django 2.1.4 on 2018-12-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='dispenser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rxit_app.Dispenser'),
        ),
    ]
