# Generated by Django 2.1.4 on 2019-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser',
            name='annotation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dxdescription',
            name='practice_type',
            field=models.CharField(choices=[('FH', 'FHT/FHN/FHO'), ('GP', 'Group'), ('SL', 'Solo')], default='SL', max_length=2),
        ),
    ]
