# Generated by Django 2.1.4 on 2018-12-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rxstats',
            name='am',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
