# Generated by Django 2.1.4 on 2019-05-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser',
            name='new_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_pt', to='rxit_app.RxStats'),
        ),
    ]
