# Generated by Django 2.1.4 on 2018-12-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pharmacists', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('num_reg_tech', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('num_unreg', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('dispenser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rxit_app.Dispenser')),
            ],
        ),
        migrations.CreateModel(
            name='RxStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_am', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('num_pm', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('num_evng', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('num_wend', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('dispenser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rxit_app.Dispenser')),
            ],
        ),
        migrations.AlterField(
            model_name='description',
            name='dispenser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rxit_app.Dispenser'),
        ),
    ]
