# Generated by Django 2.1.4 on 2019-01-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0002_auto_20190107_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dxstats',
            old_name='num_weeky',
            new_name='num_weekly',
        ),
    ]
