# Generated by Django 2.1.4 on 2019-05-02 18:25

from django.db import migrations
from rxit_app.participants.dispenser import Dispenser, RxStats

def add_rxStats_default(apps, schema_editor):
    # Get the details of the Dispenser model,
    # for each existing top level record, 
    #     create a suitable entry in the rxstats table
    #     insert the id of that that entry in the approriate ForegnKey of the main record
    
    # Dispenser = apps.get_model('rxit_app', 'Dispenser')
    # RxStats = apps.get_model('rxit_app', 'RxStats')
    dispensers = Dispenser.objects.all()
    rxStats = RxStats.objects.all()
    
    # Build a blank RxStats record
    new_rxStat_record = RxStats(
        num_am = 0,
        num_pm = 0,
        num_evng = 0,
        num_wend = 0,
        stats_notes = ''
    )

    for dispenser in dispensers:
        # Save the new record
        new_rxStat_record.save()
        dispenser.new_pt_id = new_rxStat_record.id
        dispenser.save()



class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0002_dispenser_new_pt'),
    ]

    operations = [
        migrations.RunPython(add_rxStats_default)
    ]
