# Generated by Django 2.1.4 on 2018-12-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0002_auto_20181210_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pharmacists', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('num_reg_tech', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('num_unreg', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxit_app.Dispenser')),
            ],
        ),
    ]
