# Generated by Django 2.1.4 on 2018-12-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0002_rxstats_am'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rxstats',
            old_name='am',
            new_name='num_am',
        ),
    ]
