# Generated by Django 2.1.4 on 2018-12-10 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxit_app', '0003_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='dispenser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rxit_app.Dispenser'),
        ),
    ]
