# Generated by Django 2.1.3 on 2018-11-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0006_auto_20181114_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('total_prescriptions', models.FloatField(blank=True)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rxitapp.Dispenser')),
            ],
        ),
    ]
