# Generated by Django 2.1.3 on 2018-11-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0007_dispstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispstatistics',
            name='dispenser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rxitapp.Dispenser'),
        ),
        migrations.AlterField(
            model_name='dispstatistics',
            name='username',
            field=models.CharField(blank=True, default='text', max_length=100),
        ),
    ]
