# Generated by Django 2.1.3 on 2018-11-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0008_add_relation_default_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenser',
            name='statistics',
        ),
        migrations.DeleteModel(
            name='Dispenser',
        ),
        migrations.DeleteModel(
            name='DispStat',
        ),
    ]
