# Generated by Django 2.1.3 on 2018-11-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0009_auto_20181118_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenser',
            name='statistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rxitapp.DispStatistics'),
        ),
        migrations.AlterField(
            model_name='dispstatistics',
            name='total_prescriptions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dispstatistics',
            name='username',
            field=models.CharField(default='text', max_length=100),
        ),
    ]
