# Generated by Django 2.1.3 on 2018-11-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0011_auto_20181118_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenser',
            name='statistics',
        ),
        migrations.AddField(
            model_name='dispenser',
            name='id',
            field=models.AutoField(auto_created=True, 
            primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
