# Generated by Django 2.1.3 on 2018-11-18 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0012_auto_20181118_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenser',
            name='id',
        ),
        migrations.AddField(
            model_name='dispenser',
            name='statistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rxitapp.DispStatistics'),
            preserve_default=False,
        ),
    ]
