# Generated by Django 2.1.3 on 2018-11-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxitapp', '0016_add_statistics_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser',
            name='id',
            field=models.AutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='statistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rxitapp.DispStatistics'),
        ),
    ]
